#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#111111"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color "#373737"

setxkbmap -layout us,ru -option grp:alt_shift_toggle
xset -dpms
xset s off

xcompmgr -cCfF -r5 -l-5 -t-5 -o.55 -D1

feh --bg-center $HOME/wallpapers/blackpink.jpg

conky | aebar -b -g x16 -B "#171717" -F "#FFFFFF" -f "JetBrainsMono Nerd Font Mono:size=10"
