#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          0
bspc subscribe node_add | while read -r _ _ _ node_id; do
    win_count=$(bspc query -N -d focused -n .tiled | wc -l)
    if [ "$win_count" -gt 1 ]; then
        bspc config window_gap 4
    fi
done &

bspc subscribe node_remove | while read -r _ _ _ _; do
    win_count=$(bspc query -N -d focused -n .tiled | wc -l)
    if [ "$win_count" -le 1 ]; then
        bspc config window_gap 0
    fi
done &

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#111111"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color "#11181E"

setxkbmap -layout us,ru -option grp:alt_shift_toggle

xset r rate 220 40
xset -dpms
xset s off

feh --bg-scale $HOME/wallpapers/dark.jpg

conky | aebar -b -g x16 -B "#11181E" -F "#CECECE" -f "JetBrainsMono Nerd Font Mono:size=10"
